// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypcubnibmifqcsytpyjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwY3VibmlibWlmcWNzeXRweWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDEwNzYsImV4cCI6MjA2Mjc3NzA3Nn0.orala21MU8Y7rmSeTEkyH26eXPTBZzogoUl_B3J0T4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);